name: Feature Request
description: Propose a new feature or enhancement
title: "[Feature]: "
labels: ["type: feature"]
projects: ["gumpen-app/1"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Thanks for taking the time to propose a new feature!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Brief description of the feature
      placeholder: What feature would you like to see?
    validations:
      required: true

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: Describe the feature from a user's perspective
      placeholder: |
        As a [role]
        I want [feature]
        So that [benefit]
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What needs to be true for this to be considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the system does this affect?
      options:
        - Workflow
        - Deployment
        - Schema
        - API
        - UI
        - Extensions
        - Docs
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this feature?
      options:
        - 🔴 Critical
        - 🟠 High
        - 🟡 Medium
        - 🟢 Low
      default: 2
    validations:
      required: true

  - type: dropdown
    id: size
    attributes:
      label: Estimated Size
      description: How much effort do you estimate?
      options:
        - XS (1 hour)
        - S (2-4 hours)
        - M (1 day)
        - L (2-3 days)
        - XL (1 week)
      default: 2
    validations:
      required: false

  - type: textarea
    id: technical-details
    attributes:
      label: Technical Details
      description: Implementation approach, APIs, dependencies
      placeholder: How should this be implemented?
    validations:
      required: false

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: List any blockers or dependencies
      placeholder: |
        - Depends on #123
        - Requires API access
    validations:
      required: false
